# Generated by Django 3.0.3 on 2020-06-20 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BellsTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.IntegerField(choices=[(1, 'Младшая школа'), (2, 'Средняя и старшая школа')], verbose_name='Школа')),
                ('n', models.IntegerField(verbose_name='Номер урока')),
                ('start', models.TimeField(verbose_name='Начало урока')),
                ('end', models.TimeField(verbose_name='Конец урока')),
            ],
            options={
                'verbose_name': 'Звонок',
                'verbose_name_plural': 'Звонки',
                'ordering': ['school', 'n'],
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота')], max_length=11, verbose_name='День недели')),
                ('subject', models.CharField(max_length=50, verbose_name='Предмет')),
                ('classroom', models.CharField(max_length=50, verbose_name='Кабинет')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.Grades', verbose_name='У какого класса урок')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.BellsTimeTable', verbose_name='Номер урока')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['connection', 'day', 'number'],
            },
        ),
    ]
