# Generated by Django 3.0.2 on 2020-01-24 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20200125_0154'),
        ('timetable', '0003_remove_grades_masterteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.Grades', verbose_name='У какого класса урок'),
        ),
        migrations.DeleteModel(
            name='Grades',
        ),
    ]
