# Generated by Django 3.0.2 on 2020-01-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20200125_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='letter',
            field=models.CharField(choices=[('А', 'А'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г'), ('Д', 'Д'), ('Е', 'Е'), ('Ж', 'Ж'), ('З', 'З'), ('И', 'И'), ('К', 'К')], max_length=1, verbose_name='Литера'),
        ),
    ]
