# Generated by Django 3.2 on 2021-04-10 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_averagevalues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klasses',
            name='head_teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='klass', to='core.teachers', verbose_name='Классный руководитель'),
        ),
    ]
