# Generated by Django 3.0.2 on 2020-02-09 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200119_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publications',
            options={'ordering': ['-publication_date'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
