# Generated by Django 3.2 on 2021-04-13 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BellsTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.IntegerField(choices=[(1, 'Младшая школа'), (2, 'Средняя и старшая школа')], verbose_name='Школа')),
                ('n', models.IntegerField(verbose_name='Номер урока')),
                ('start', models.TimeField(verbose_name='Начало урока')),
                ('end', models.TimeField(verbose_name='Конец урока')),
            ],
            options={
                'verbose_name': 'Звонок',
                'verbose_name_plural': 'Звонки',
                'ordering': ['school', 'n'],
                'unique_together': {('school', 'n')},
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], verbose_name='День недели')),
                ('classroom', models.CharField(max_length=50, verbose_name='Кабинет')),
                ('klass', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.klasses', verbose_name='Класс')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.bellstimetable', verbose_name='Номер урока')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subjects', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['klass', 'day', 'number'],
            },
        ),
    ]
