# Generated by Django 3.2 on 2021-04-10 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_klasses_head_teacher'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='day',
            field=models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='klass',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.klasses', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subjects', verbose_name='Предмет'),
        ),
        migrations.DeleteModel(
            name='Klasses',
        ),
    ]
