# Generated by Django 3.0.2 on 2020-01-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20200125_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('second_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('email', models.EmailField(default='test', max_length=50, verbose_name='Почта')),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'администратор',
                'verbose_name_plural': 'Администраторы',
                'ordering': ['surname', 'first_name', 'second_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['surname', 'first_name', 'second_name'], 'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.RemoveField(
            model_name='marks',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='students',
            name='login',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='login',
        ),
        migrations.AddField(
            model_name='marks',
            name='mark',
            field=models.IntegerField(choices=[(5, '5 - отлично'), (4, '4 - хорошо'), (3, '3 - удовлетворительно'), (2, '2 - плохо'), (1, '1 - ужасно')], default=5, verbose_name='оценка'),
        ),
        migrations.AddField(
            model_name='students',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(default='test', max_length=50, unique=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='students',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='email',
            field=models.EmailField(default='test', max_length=50, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
