# Generated by Django 3.0.2 on 2020-02-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20200130_1909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administration',
        ),
        migrations.RemoveField(
            model_name='hometasks',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='hometasks',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='student',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='students',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='subjects',
        ),
        migrations.DeleteModel(
            name='Grades',
        ),
        migrations.DeleteModel(
            name='HomeTasks',
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
