# Generated by Django 3.0.2 on 2020-02-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
