# Generated by Django 3.0.2 on 2020-02-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_auto_20200206_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почта'),
        ),
    ]
