# Generated by Django 3.0.2 on 2020-02-07 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0013_auto_20200207_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['grade', 'surname', 'first_name', 'second_name'], 'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученик'},
        ),
        migrations.AlterField(
            model_name='students',
            name='grade',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diary.Grades', verbose_name='Класс'),
        ),
    ]
