# Generated by Django 3.0.2 on 2020-02-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0015_auto_20200208_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['grade', 'surname', 'first_name', 'second_name'], 'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AlterField(
            model_name='students',
            name='second_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Отчество'),
        ),
    ]
