# Generated by Django 3.0.2 on 2020-02-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0017_administrators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='password',
        ),
    ]
